### ISSUE TITLE
Missing VC container

### ISSUE THREAD

**Issue by spinfish** [spinfish/amethyst#4]
#### Not epic moment
![oh god fix the vc container issue](https://user-images.githubusercontent.com/62459597/146717483-b5404ba0-5d67-49c4-baa9-5b4c698ff5ae.png)

#### Quick fix but looks weird when not in a VC
```css
#app-mount .wrapper-24pKcD {
    display: unset;
}
.wrapper-24pKcD > .container-1giJp5 {
    border-bottom: none;
}
```
